name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements-test.txt
          pip install -r requirements.txt

  trigger-cd:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.event.action == 'push' && success()

    steps:
      - name: Trigger CD Workflow
        uses: actions/github-script@0.10.0
        with:
          script: |
            const { data: workflows } = await octokit.request('GET /repos/{owner}/{repo}/actions/workflows', {
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const cdWorkflow = workflows.workflows.find(workflow => workflow.name === 'Continuous Deployment');

            if (cdWorkflow) {
              const { data: run } = await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: cdWorkflow.id
              });

              console.log(`Triggered CD Workflow: ${run.html_url}`);
            } else {
              console.error('CD Workflow not found.');
            }